version: '3.8'
services:
  db:
    image: postgres:16
    container_name: adonis_db
    restart: always
    environment:
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: adonis
      POSTGRES_DB: clicksoft
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
